### ISSUE TITLE
Color of text

### ISSUE THREAD

**Issue by Quantum-Codes** [Turtle84375/turtle84375.tk#40]
The color grey doesn't look clearly in the white background. I can't read it. Make it a bit darker. (I can't find the color in style.css. only found in the water.css file)

**Comment by Turtle84375** [comment]
@Quantum-Codes I don't think I have any grey-on-white, but could you post a screenshot of what you're talking about?

**Comment by Quantum-Codes** [comment]
![chrome_screenshot_1644067266762](https://user-images.githubusercontent.com/87054411/152643844-b9b87dcf-c93b-49cc-82ac-c3439358ae3c.png)
You may check for other pages too! 
I think 404 pages have the same problem

**Comment by Turtle84375** [comment]
What the heck?

This is what I see when I visit the page:
![Screenshot 2022-02-05 9 40 12 AM](https://user-images.githubusercontent.com/91347263/152656447-d9ac6e4e-601e-4bf4-b4d4-b657ad029afe.png)

I'm gonna make a wild guess and assume you're viewing the site on a mobile device... 😂

The site is pretty much anti-mobile support if you couldn't tell already, and I'm not entirely sure how to fix it since I'm using a predefined CSS template (water.css). I guess I could override everything the main.css, but CSS isn't my strong suit.

**Comment by Quantum-Codes** [comment]
Yes I using a mobile (tab) on dark mode lol. Idk what's the problem. Is there dark mode in this? I saw dark mode in that template.. maybe that's messed up

**Comment by Turtle84375** [comment]
Yeah, that's it, I'm redoing all of the CSS lol...

If anyone could help me make it mobile-friendly that'd be nice :)

**Comment by Turtle84375** [comment]
Stalled until #36 is resolved.
